
### Google auth
POST http://localhost:8000/oauth/google
Content-Type: application/json

{
    "access_token": ""
}

### Facebook auth
POST http://localhost:8000/oauth/facebook
Content-Type: application/json

{
    "access_token": ""
}


### Join by email
POST http://localhost:8000/join
Content-Type: application/json

{
    "email": "aymen@gmail.com",
    "password": "123456",
    "firstname": "aymen",
    "lastname": "jdida"
}

### Login by email
POST http://localhost:8000/login
Content-Type: application/json

{
    "email": "wassimbenjdida@gmail.com",
    "password": "123456"
}


### logout
POST http://localhost:8000/logout